package org.sooo;
/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
@SuppressWarnings("all")
/** A pair of strings. */
public class Pair extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Pair\",\"doc\":\"A pair of strings.\",\"fields\":[{\"name\":\"left\",\"type\":\"string\"},{\"name\":\"right\",\"type\":\"string\"}]}");
  @Deprecated public java.lang.CharSequence left;
  @Deprecated public java.lang.CharSequence right;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return left;
    case 1: return right;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: left = (java.lang.CharSequence)value$; break;
    case 1: right = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'left' field.
   */
  public java.lang.CharSequence getLeft() {
    return left;
  }

  /**
   * Sets the value of the 'left' field.
   * @param value the value to set.
   */
  public void setLeft(java.lang.CharSequence value) {
    this.left = value;
  }

  /**
   * Gets the value of the 'right' field.
   */
  public java.lang.CharSequence getRight() {
    return right;
  }

  /**
   * Sets the value of the 'right' field.
   * @param value the value to set.
   */
  public void setRight(java.lang.CharSequence value) {
    this.right = value;
  }

  /** Creates a new Pair RecordBuilder */
  public static Pair.Builder newBuilder() {
    return new Pair.Builder();
  }
  
  /** Creates a new Pair RecordBuilder by copying an existing Builder */
  public static Pair.Builder newBuilder(Pair.Builder other) {
    return new Pair.Builder(other);
  }
  
  /** Creates a new Pair RecordBuilder by copying an existing Pair instance */
  public static Pair.Builder newBuilder(Pair other) {
    return new Pair.Builder(other);
  }
  
  /**
   * RecordBuilder for Pair instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Pair>
    implements org.apache.avro.data.RecordBuilder<Pair> {

    private java.lang.CharSequence left;
    private java.lang.CharSequence right;

    /** Creates a new Builder */
    private Builder() {
      super(Pair.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Pair.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Pair instance */
    private Builder(Pair other) {
            super(Pair.SCHEMA$);
      if (isValidValue(fields()[0], other.left)) {
        this.left = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.left);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.right)) {
        this.right = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.right);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'left' field */
    public java.lang.CharSequence getLeft() {
      return left;
    }
    
    /** Sets the value of the 'left' field */
    public Pair.Builder setLeft(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.left = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'left' field has been set */
    public boolean hasLeft() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'left' field */
    public Pair.Builder clearLeft() {
      left = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'right' field */
    public java.lang.CharSequence getRight() {
      return right;
    }
    
    /** Sets the value of the 'right' field */
    public Pair.Builder setRight(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.right = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'right' field has been set */
    public boolean hasRight() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'right' field */
    public Pair.Builder clearRight() {
      right = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Pair build() {
      try {
        Pair record = new Pair();
        record.left = fieldSetFlags()[0] ? this.left : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.right = fieldSetFlags()[1] ? this.right : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
